### Import Library Tensorflow

In [74]:
import tensorflow as tf

### Membuat Tensor shape (5, 5) dengan nilai random dan disimpan ke dalam variable random_tensor

In [75]:
random_tensor = tf.random.normal([5, 5])
random_tensor

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[-1.4204061 ,  0.96488476, -0.8710978 , -1.7372956 ,  0.8904632 ],
       [ 0.7798779 ,  0.5186624 ,  3.064286  , -0.42675173, -0.01197859],
       [ 0.92959887,  0.96473014, -1.0938528 ,  0.51005787,  0.7880065 ],
       [-0.11182619,  0.50889623, -0.2681347 ,  0.10837378,  0.9259073 ],
       [ 0.0942755 , -0.38526744, -1.0757197 ,  1.1518054 , -0.11730836]],
      dtype=float32)>

### Membuat Tensor shape (5, 5) dari sebuah list dengan nilai bilangan prima dan disimpan ke dalam variable prime_tensor

In [76]:
prime_tensor = tf.constant([2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97], shape = [5,5], dtype = tf.float32)
prime_tensor

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 2.,  3.,  5.,  7., 11.],
       [13., 17., 19., 23., 29.],
       [31., 37., 41., 43., 47.],
       [53., 59., 61., 67., 71.],
       [73., 79., 83., 89., 97.]], dtype=float32)>

### Menampilkan dimensi dari kedua variable di atas

#### Dimensi dari variable random_tensor

In [77]:
dimensi_random = tf.random.normal([5,5], seed=1)
dimensi_random.shape

TensorShape([5, 5])

#### Dimensi dari variable prime_tensor

In [78]:
dimensi_prime = tf.constant([2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97], shape = [5,5])
dimensi_prime.shape

TensorShape([5, 5])

### Menampilkan hasil dari perhitungan aritmatika 2 variable di atas

#### Deklarasi varible x dan y

In [79]:
x = random_tensor
y = prime_tensor

#### Pertambahan

In [80]:
tf.add(x, y)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 0.5795939,  3.9648848,  4.1289024,  5.2627044, 11.890463 ],
       [13.779878 , 17.518661 , 22.064285 , 22.573248 , 28.988022 ],
       [31.9296   , 37.96473  , 39.906147 , 43.51006  , 47.788006 ],
       [52.888172 , 59.508896 , 60.731865 , 67.108376 , 71.92591  ],
       [73.09428  , 78.61473  , 81.92428  , 90.1518   , 96.88269  ]],
      dtype=float32)>

#### Pengurangan

In [81]:
tf.subtract(x, y)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ -3.420406 ,  -2.0351152,  -5.8710976,  -8.737295 , -10.109537 ],
       [-12.220122 , -16.481339 , -15.935714 , -23.426752 , -29.011978 ],
       [-30.0704   , -36.03527  , -42.093853 , -42.48994  , -46.211994 ],
       [-53.111828 , -58.491104 , -61.268135 , -66.891624 , -70.07409  ],
       [-72.90572  , -79.38527  , -84.07572  , -87.8482   , -97.11731  ]],
      dtype=float32)>

#### Perkalian

In [82]:
tf.matmul(x, y)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[-44.374195, -52.24264 , -56.550816, -62.355286, -65.55747 ],
       [ 79.802956,  98.41081 , 112.36362 , 119.494225, 136.18001 ],
       [ 65.04879 ,  71.062584,  74.64797 ,  85.966774,  99.44242 ],
       [ 71.41486 ,  77.9355  ,  81.577484,  89.05883 ,  98.43312 ],
       [ 14.314938,  12.620808,   9.570325,  12.273351,   9.704722]],
      dtype=float32)>

#### Pembagian

In [83]:
tf.divide(x, y)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[-7.1020305e-01,  3.2162824e-01, -1.7421956e-01, -2.4818508e-01,
         8.0951199e-02],
       [ 5.9990607e-02,  3.0509552e-02,  1.6127820e-01, -1.8554423e-02,
        -4.1305480e-04],
       [ 2.9987060e-02,  2.6073787e-02, -2.6679335e-02,  1.1861810e-02,
         1.6766096e-02],
       [-2.1099281e-03,  8.6253602e-03, -4.3956512e-03,  1.6175191e-03,
         1.3040948e-02],
       [ 1.2914452e-03, -4.8768031e-03, -1.2960479e-02,  1.2941633e-02,
        -1.2093646e-03]], dtype=float32)>

#### Pangkat

In [84]:
tf.pow(x, y)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 2.0175536e+00,  8.9831024e-01, -5.0157350e-01, -4.7765694e+01,
         2.7911013e-01],
       [ 3.9477166e-02,  1.4224628e-05,  1.7388280e+09, -3.1191176e-09,
        -0.0000000e+00],
       [ 1.0403109e-01,  2.6486000e-01, -3.9565212e+01,  2.6769258e-13,
         1.3705668e-05],
       [-0.0000000e+00,  4.9104903e-18, -1.3475210e-35,  0.0000000e+00,
         4.2295437e-03],
       [ 0.0000000e+00, -1.8846121e-33, -4.2759006e+02,  2.9022903e+05,
        -0.0000000e+00]], dtype=float32)>

### Menampilkan Nilai Maksimum dan Minimum dari varible random_tensor

#### Deklarasi variable argmax

In [85]:
argmax = random_tensor

#### Untuk Melihat Lokasi Nilai Max per kolom

In [86]:
max1 = tf.argmax(argmax, axis = 0) 
max1

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([2, 0, 1, 4, 3], dtype=int64)>

#### Untuk Melihat Lokasi Nilai Max per baris

In [87]:
max2 = tf.argmax(argmax, axis = 1)
max2

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([1, 2, 1, 4, 3], dtype=int64)>

#### Deklarasi variable argmin

In [88]:
argmin = random_tensor

#### Untuk Melihat Lokasi Nilai Max per kolom

In [89]:
min1 = tf.argmin(argmin, axis = 0)
min1

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([0, 4, 2, 0, 4], dtype=int64)>

#### Untuk Melihat Lokasi Nilai Max per baris

In [90]:
min2 = tf.argmin(argmin, axis = 1)
min2

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([3, 3, 2, 2, 2], dtype=int64)>

### Menampilkan hasil dari penggabungan variable random_tensor dengan prime_tensor (concatenation)

In [91]:
concat1 = random_tensor
concat2 = prime_tensor

In [92]:
concat1dan2 = tf.concat([concat1, concat2], axis = 0)
concat1dan2

<tf.Tensor: shape=(10, 5), dtype=float32, numpy=
array([[-1.42040610e+00,  9.64884758e-01, -8.71097803e-01,
        -1.73729563e+00,  8.90463173e-01],
       [ 7.79877901e-01,  5.18662393e-01,  3.06428599e+00,
        -4.26751733e-01, -1.19785890e-02],
       [ 9.29598868e-01,  9.64730144e-01, -1.09385276e+00,
         5.10057867e-01,  7.88006485e-01],
       [-1.11826189e-01,  5.08896232e-01, -2.68134713e-01,
         1.08373776e-01,  9.25907314e-01],
       [ 9.42755044e-02, -3.85267437e-01, -1.07571971e+00,
         1.15180540e+00, -1.17308363e-01],
       [ 2.00000000e+00,  3.00000000e+00,  5.00000000e+00,
         7.00000000e+00,  1.10000000e+01],
       [ 1.30000000e+01,  1.70000000e+01,  1.90000000e+01,
         2.30000000e+01,  2.90000000e+01],
       [ 3.10000000e+01,  3.70000000e+01,  4.10000000e+01,
         4.30000000e+01,  4.70000000e+01],
       [ 5.30000000e+01,  5.90000000e+01,  6.10000000e+01,
         6.70000000e+01,  7.10000000e+01],
       [ 7.30000000e+01,  7.90000

### Menampilkan hasil sorting dari kedua variable di atas (descending)

In [93]:
sort1 = random_tensor
sort2 = prime_tensor

In [94]:
sort_desc = tf.sort([sort1, sort2], direction="DESCENDING")
sort_desc

<tf.Tensor: shape=(2, 5, 5), dtype=float32, numpy=
array([[[ 9.64884758e-01,  8.90463173e-01, -8.71097803e-01,
         -1.42040610e+00, -1.73729563e+00],
        [ 3.06428599e+00,  7.79877901e-01,  5.18662393e-01,
         -1.19785890e-02, -4.26751733e-01],
        [ 9.64730144e-01,  9.29598868e-01,  7.88006485e-01,
          5.10057867e-01, -1.09385276e+00],
        [ 9.25907314e-01,  5.08896232e-01,  1.08373776e-01,
         -1.11826189e-01, -2.68134713e-01],
        [ 1.15180540e+00,  9.42755044e-02, -1.17308363e-01,
         -3.85267437e-01, -1.07571971e+00]],

       [[ 1.10000000e+01,  7.00000000e+00,  5.00000000e+00,
          3.00000000e+00,  2.00000000e+00],
        [ 2.90000000e+01,  2.30000000e+01,  1.90000000e+01,
          1.70000000e+01,  1.30000000e+01],
        [ 4.70000000e+01,  4.30000000e+01,  4.10000000e+01,
          3.70000000e+01,  3.10000000e+01],
        [ 7.10000000e+01,  6.70000000e+01,  6.10000000e+01,
          5.90000000e+01,  5.30000000e+01],
        [ 9